Repository techequilla/community_website_boilerplate, pull requests merged in 2020-03, with the labels that each got.

#2 Created Bug Report Issue Template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: rgsoc20, template

#3 Create Feature Request Template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: rgsoc20, template

#4 Create Pull Request Template
  .github/pull_request_template.md
Labels: rgsoc20, template

#6 Documentation
  README.MD
  contribute.md
  guide.md
  snapshots/1.png
  snapshots/2.png
  snapshots/3.png
  snapshots/4.png
  snapshots/5.png
Labels: documentation, rgsoc20

#7 Corrected the Redirections
  README.MD
Labels: bug, rgsoc20

#8 Added Home Page Layout
  HomeBG.png
  css/index.css
  index.html
Labels: documentation, rgsoc20

#9 Added Teams Page Layout
  css/teams.css
  teams.html
Labels: documentation, rgsoc20

#11 Added Dark Mode and Better UI
  css/index.css
  index.html
  webtech-1.jpg
Labels: enhancement, rgsoc20

#12 Made Home Page Responsive
  HomeBG.png
  css/index.css
  index.html
Labels: enhancement, rgsoc20

#13 Teams Page Dark Theme and Responsive
  css/teams.css
  teams.html
  teamsc.jpg
Labels: rgsoc20

#14 Added Contact Us Page
  ContactUs.jpg
  contactUs.html
  css/contactUs.css
  css/forms.css
  index.html
Labels: rgsoc20

#16 Made Contact Us Responsive and Added Redirections
  contactUs.html
  css/contactUs.css
  css/forms.css
  index.html
  teams.html
Labels: enhancement, rgsoc20
