Repository techequilla/community_website_boilerplate, pull requests merged in 2020-04, with the labels that each got.

#23 Improved Documentation, Added CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
  README.MD
Labels: rgsoc20

#27 added project page. issue #19 Primary Task Done
  css/projects.css
  projects.html
Labels: rgsoc20

#29 Update Index.html
  index.html
Labels: enhancement, rgsoc20

#30 Folders cleaned, Added redirections, Responsiveness
  ContactUs.jpg
  assets/Icons/GitHub_Mark.png
  assets/Icons/Instagram.png
  assets/Icons/YouTube.png
  assets/Icons/faceBook.png
  assets/Icons/gmail.png
  assets/Icons/inter.png
  assets/Icons/linkedin.png
  assets/Icons/location.png
  assets/Icons/opensource.png
  assets/Icons/publics.png
  assets/Icons/research.png
  assets/Icons/twitter.png
  assets/Images/sub-header-bg.jpg
  assets/Images/teamsc.jpg
  assets/Images/webtech-1.jpg
  blog.html
  contactUs.html
  css/blog.css
  css/index.css
  index.html
  teams.html
Labels: PR: unreviewed, bug, rgsoc20

#31 Improve Project Page
  contactUs.html
  index.html
  projects.html
  teams.html
Labels: PR: unreviewed, enhancement, rgsoc20

#33 Minor Bug Correction
  teams.html
Labels: PR: unreviewed, bug, rgsoc20

#39 Updated Burger Button for Dark Mode
  contact.html
  index.html
  projects.html
  teams.html
Labels: PR: unreviewed, enhancement, rgsoc20

#42 Added Achievements Page
  achievements.html
  assets/Images/trophy.jpg
  contact.html
  css/achievements.css
  index.html
  projects.html
  teams.html
Labels: PR: unreviewed, enhancement, rgsoc20

#41 Remove Bug
  css/contactUs.css
  css/index.css
  css/projects.css
  css/teams.css
Labels: PR: unreviewed, bug, rgsoc20

#45 Add Dark Mode to Achievements Page
  css/achievements.css
Labels: PR: unreviewed, enhancement, rgsoc20

#46 bug removed from the achievement page
  css/achievements.css
Labels: PR: unreviewed, enhancement, rgsoc20, ui/ux

#47 Added announcement page
  announcement.html
  css/announcements.css
Labels: PR: unreviewed, rgsoc20
